export const cart = [
  {
    id: 1,
    title: 'Product 1',
    description: 'Description of product 1',
    price: 200,
    discountPercentage: 10,
    rating: 4,
    stock: 94,
    brand: 'Brand 1',
    category: 'category 1',
    thumbnail: 'https://picsum.photos/200/300',
    images: [''],
  },
  {
    id: 2,
    title: 'Product 2',
    description: 'Description of product 2',
    price: 300,
    discountPercentage: 20,
    rating: 4,
    stock: 94,
    brand: 'Brand 2',
    category: 'category 2',
    thumbnail: 'https://picsum.photos/200/400',
    images: [''],
  },
];
